//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSıstemıProjeOdev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.OduncIslemleri = new HashSet<OduncIslemleri>();
        }
    
        public int Id { get; set; }
        public string BarkodNo { get; set; }
        public string KitapAd { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> YayinYili { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string KapakFotografi { get; set; }
        public int ToplamStok { get; set; }
        public int MevcutStok { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemleri> OduncIslemleri { get; set; }
    }
}
