//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSıstemıProjeOdev
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncIslemleri
    {
        public int Id { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string KondisyonDurumu { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
